version: 2.1

jobs:
  node-tests:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - run:
          name: "Node tests"
          command: npm run-script integration

workflows:
  test:
    jobs:
      - node-tests:
          version: '12'
          name: node-12
